language: objective-c
osx_image: xcode10.2

env:
  global:
  - WORKSPACE=WebexSDK.xcworkspace
  - SCHEME=WebexSDK
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone Xs,OS=12.2"      CONFIGURATION="ReleaseTest" IsIntegrationTestingTask="true"
    - DESTINATION="platform=iOS Simulator,name=iPhone 8 Plus,OS=11.4"  CONFIGURATION="ReleaseTest"
before_install:
  - gem install cocoapods --pre
  - pod repo update > /dev/null
  # - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - brew install sendemail
script:
  - set -o pipefail
  # - travis_wait 3 bash StartIntegrationTest.sh
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration "$CONFIGURATION" CLIENTSECRET="$CLIENTSECRET" test | xcpretty -c
  # - travis_wait 50 bash FetchTestingResult.sh
branches:
